# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 2.1.8
_src_path: gh:algorandfoundation/algokit-fullstack-template
author_email: premshyam48@gmail.com
author_name: Premkumar1845
contract_name: probex_contract
deployment_language: python
preset_name: starter
project_name: ProBex

